# fly.toml app configuration file generated for trainercontainer on 2024-02-14T15:19:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trainercontainer'
primary_region = 'cdg'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"


[env]
  APP_NAME = 'trainercontainer'
  APP_ENV = 'production'
  APP_URL = "https://trainercontainer.fly.dev"
  DB_CONNECTION= "mysql"
  DB_HOST = "trainercontainer-1.c96k400u8cmx.eu-central-1.rds.amazonaws.com"
  DB_PORT = "3306"
  DB_DATABASE = "trainercontainer"
  DB_USERNAME = "trainercontainer"
  AWS_DEFAULT_REGION = "eu-central-1"
  AWS_BUCKET= "trainercontainer"
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  FILESYSTEM_DRIVER = "s3"
  AWS_URL = "https://trainercontainer.s3.eu-central-1.amazonaws.com/"
  SIDECAR_REGION = "eu-central-1"
  SIDECAR_ARTIFACT_BUCKET_NAME = "sidecar-eu-central-1-1708983940"
  SIDECAR_EXECUTION_ROLE = "arn:aws:iam::058264436509:role/sidecar-execution-role"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
